os:
  - linux

before_install:
  - sudo apt-get -qq install lib32stdc++6

install:
  - wget http://isabelle.in.tum.de/dist/Isabelle2016-1_app.tar.gz
  - tar -xzvf Isabelle2016-1_app.tar.gz

cache:
  directories:
    - $HOME/.isabelle

script:
  Isabelle2016-1/bin/isabelle build -v -D .
