# Copyright 2017, Data61, CSIRO
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(DATA61_GPL)

resolver: lts-2.22

packages: []
extra-deps: []

flags: {}
extra-package-dbs: []
